/* Bump the cache stamp.  node tools/stamp.mjs
   Rewrites every ?v= in index.html AND plate.html AND version.txt from one value.
   version.txt on its own is a lie: the ?v= stamps are the real cache key.

   This hub has TWO pages — index.html (the body in 3D) and plate.html (the light version) —
   and they must carry the same stamp, or one is served stale against the other's files.
   Before this tool existed the stamps here were kept by hand, and they drifted. */
import { readFileSync, writeFileSync, existsSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const STAMP = String(Math.floor(Date.now() / 1000));

/* ---------- the shared progress files ----------
   labs-shared/labs.json is the single register of labs — one place for each lab's question
   count, the shelf it sits behind, and the localStorage key it keeps progress under (which is
   NOT always <id>.v2). labs-shared/progress.js is the only code that knows how to read a
   lab's record, so this hub never has to know a lab's internals. Both are copied in here, so
   the published site is self-contained: adding a lab means editing labs.json and rebuilding.

   NOTHING SCHOOL-SPECIFIC IS COPIED. This hub is one repository, linked from both the NLCS
   and the open edition of the front door, so it must never carry a marks address. It shows
   only what a student's own browser remembers; signing in and bringing handed-in work back
   belongs to the front door, where each school sets its own address in js/local.js. */
function findShared(from) {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(resolve(dir, 'labs-shared/labs.json'))) return resolve(dir, 'labs-shared');
    const up = resolve(dir, '..'); if (up === dir) break; dir = up;
  }
  return null;
}
const SHARED = findShared(REPO);
if (SHARED) {
  mkdirSync(resolve(REPO, 'js/data'), { recursive: true });
  copyFileSync(resolve(SHARED, 'labs.json'), resolve(REPO, 'js/data/labs.json'));
  const reg = readFileSync(resolve(SHARED, 'labs.json'), 'utf8');
  writeFileSync(resolve(REPO, 'js/data/labs.js'),
    '/* GENERATED by tools/stamp.mjs from labs-shared/labs.json — do not edit. */\n' +
    'window.LABS_REGISTER = ' + reg.trim() + ';\n');
  copyFileSync(resolve(SHARED, 'progress.js'), resolve(REPO, 'js/progress.js'));
  console.log('  shared        labs.json + progress.js copied in');
} else {
  console.error('  labs-shared/ not found above ' + REPO + ' — progress files not refreshed');
}

let total = 0;
for (const page of ['index.html', 'plate.html']) {
  const f = resolve(REPO, page);
  if (!existsSync(f)) continue;
  const html = readFileSync(f, 'utf8');
  const n = (html.match(/\?v=\d+/g) || []).length;
  if (!n) { console.error(page + ' carries no ?v= stamps'); process.exit(1); }
  /* assets/model/body.glb?v=4 is the model's OWN version — it changes when the model does,
     not when the code does, and re-downloading 8 MB on every deploy is not free. Leave it. */
  writeFileSync(f, html.replace(/(?<!body\.glb)\?v=\d+/g, '?v=' + STAMP));
  total += n;
  console.log('  ' + page.padEnd(13) + n + ' stamp(s)');
}
if (!total) { console.error('nothing stamped'); process.exit(1); }
writeFileSync(resolve(REPO, 'version.txt'), STAMP + '\n');
console.log('stamped ' + total + ' assets and version.txt with ' + STAMP);
